### ISSUE TITLE
fix to allow many more patients

### ISSUE THREAD

**Issue by bradymiller** [openemr/demo-data-generator#5]
@MatthewVita and @robertdown ,
I don't know python very well, but I think storing everything in array as build the demoset will really be limiting. Isn't there a way to throw each `patient` into output via the `generate_sql` function rather than push it into an array?
(I know the work around is to just run the script multiple times, but then you lose ability to increment things like pid)

**Comment by bradymiller** [comment]
btw, here is the error I get when have too many patients (what is odd is that it is not consistent how many patient it happens; occasionally I can build 10000 patients, but other times I get below error when try to just build 3000 patients; perhaps one of the random entries is producing something that breaks something???):
``````
Traceback (most recent call last):
  File "/home/brady2/git/demo-data-generator/venv/bin/demodata", line 11, in <module>
    sys.exit(cli())
  File "/home/brady2/git/demo-data-generator/venv/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/brady2/git/demo-data-generator/venv/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/brady2/git/demo-data-generator/venv/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/brady2/git/demo-data-generator/venv/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/brady2/git/demo-data-generator/venv/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/brady2/git/demo-data-generator/venv/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/brady2/git/demo-data-generator/venv/local/lib/python2.7/site-packages/demodata/scripts/entry.py", line 22, in patients
    patient = p.generate_patients(count)
  File "/home/brady2/git/demo-data-generator/venv/local/lib/python2.7/site-packages/demodata/scripts/patient.py", line 34, in generate_patients
    'drivers_license': random_drivers_license(lname[0], int(dob.strftime("%y"))),
IndexError: string index out of range
``````
